#!/bin/bash
# vim:et:ai:sw=2:tw=0:ft=bash
# copyright 2025, thias <github.attic@typedef.net>, CC BY 4.0

IMAGE='x4sdlfix'

# tag this image with the libSDL git tag used
read x LIBSDL_TAG < <(grep '^ARG LIBSDL_TAG' Containerfile)
eval "${LIBSDL_TAG}"; LIBSDL_TAG="${LIBSDL_TAG#*-}"

TAGS=( ${LIBSDL_TAG:+"${LIBSDL_TAG}"} 'latest' )

unset TAGSARGV; [ -n "${IMAGE}" ] && {
  for TAG in "${TAGS[@]:-latest}"; do
    TAGSARGV+=( '-t' "${IMAGE}:${TAG}" )
  done
}

# non OCI compliant image format stuff
#TAGSARGV+=( '--format' 'docker' )

#docker build ${TAGSARGV:+${TAGSARGV[*]}} "${@}" "${0%/*}"
podman build ${TAGSARGV:+${TAGSARGV[*]}} "${@}" "${0%/*}"

